### ISSUE TITLE
Check if coffea Hist is depreciated

### ISSUE THREAD

**Issue by bryates** [TopEFT/topeft#345]

**Comment by kmohrman** [comment]
Just to add some description to this issue, it would be good to know the following: 
* On what date does (or did) coffea hist officially become depreciated, i.e. no longer supported or updated
* On what date does the warning about the depreciation change to an error
* What are the immediate consequences for topcoffea (e.g. do we expect the CI to start failing?) 
* If the consequences inhibit our ability to run (e.g. if the warning becomes and error and the processor crashes) then we should implement at least a temporary workaround (e.g. pinning the coffea version, or copying the coffea hist code to topeft and maintaining it privately until we can upgrade)

**Comment by kmohrman** [comment]
Then I am wondering if you or @emcgrady understand why our CI continues to run fine without crashing?

**Comment by abasnet97** [comment]
Hmm good point. Maybe Dec 2022 was the target date for coffea v0.8.0 release but perhaps got pushed back. Not sure!

**Comment by abasnet97** [comment]
Based on a recent message posted by Lindsey Gray (one of the coffea developers) on Coffea Users Mattermost channel (March 14, 2023), coffea 2023 (which was initially called v0.8) is still a work in progress  and nearing completion soon. That might be why we still have our CI passing.

**Comment by abasnet97** [comment]
Update: Based on Lindsey's recent message on Coffea Users Mattermost channel (on Apr 6, 2023), it seems like a first release candidate of coffea 2023 is out now. The caveat is that it is only on pypi for now (won't be on conda until full release).

**Comment by kmohrman** [comment]
Coffea hist is indeed out of date. HistEFT will be replaced by histEFT see [PR#371](https://github.com/TopEFT/topeft/pull/371)
