### ISSUE TITLE
Correction-lib CI branch

### ISSUE THREAD

**Issue by bryates** [TopEFT/topeft#432]
Set the CI checkout back to the main branch once https://github.com/TopEFT/topcoffea/pull/43 is merged.
https://github.com/TopEFT/topeft/blob/6866198c5a5fd81b8eac655c10919f5dba48f476/.github/workflows/main.yml#L90

**Comment by bryates** [comment]
@anpicci now that https://github.com/TopEFT/topcoffea/pull/43 was merged, can you please update the CI on https://github.com/TopEFT/topeft/pull/430 to remove the `--branch` call in TopCoffea?

**Comment by anpicci** [comment]
@bryates I have done that
